function FullWidthContentJSON(key){

var val="Full Width Content"
if(isNaN(parseInt(key)) ){
	val="Full Width Content";
}
else {
	val="Full Width Content "+key;
}
	return {
	"fields": [{
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Header",
		"partnerEditable": true,
		"fieldType": "header",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4daa45eee",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "http://static.ziftsolutions.com/files/8a9983f36ef6ff4b016f060bcf323d66/1000x365.png",
		"supplierPartnerEditable": false,
		"name": ""+val+" Image",
		"partnerEditable": true,
		"fieldType": "embeddedimage",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dac45ef0",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Image Alt Copy",
		"partnerEditable": true,
		"fieldType": "edit",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dad25ef1",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "No",
		"supplierPartnerEditable": false,
		"name": ""+val+" Gate Option",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "Yes,No",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dae45ef2",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "Library Asset",
		"supplierPartnerEditable": false,
		"name": ""+val+" Link Option",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "Library Asset,Print Media,Web Plugin,URL,None",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4daf35ef3",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "File or URL",
		"supplierPartnerEditable": false,
		"name": ""+val+" Link Type",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "File or URL,Video",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983f36ef6ff4b016f0547a1ab3bfc",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a9982986f1a9c1c016f240942b22f7b",
		"supplierPartnerEditable": false,
		"name": ""+val+" Library Asset",
		"partnerEditable": false,
		"fieldType": "librarycontent",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "8a9983796f1f36b7016f1ffba83b01c5",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db045ef4",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a99836d66444ce201665527c1912e63",
		"supplierPartnerEditable": false,
		"name": ""+val+" Print Media",
		"partnerEditable": true,
		"fieldType": "print",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db145ef5",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a99827a677710b801677b083bfc1691",
		"supplierPartnerEditable": false,
		"name": ""+val+" Web Plugin",
		"partnerEditable": true,
		"fieldType": "static_panel",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db235ef6",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" URL",
		"partnerEditable": false,
		"fieldType": "url",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db325ef7",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Asset Override",
		"partnerEditable": true,
		"fieldType": "edit",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": false,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db425ef8",
		"hiddenOption": "",
		"viewableByAgency": false
	}]
}

}
