function FullWidthBannerJSON(key){

var val="Full Width Banner"
if(isNaN(parseInt(key)) ){
	val="Full Width Banner";
}
else {
	val="Full Width Banner "+key;
}
	return {
	"fields": [{
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Header",
		"partnerEditable": true,
		"fieldType": "header",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db505ef9",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "#333333",
		"supplierPartnerEditable": false,
		"name": ""+val+" Copy Color",
		"partnerEditable": false,
		"fieldType": "colorpicker",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db6b5efb",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Background Image",
		"partnerEditable": false,
		"fieldType": "embeddedimage",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db865efd",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "#ffffff",
		"supplierPartnerEditable": false,
		"name": ""+val+" Background Color",
		"partnerEditable": false,
		"fieldType": "colorpicker",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db795efc",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "http://static.ziftsolutions.com/files/8a9983f36ef6ff4b016f060eb6cf3d95/670x670.png",
		"supplierPartnerEditable": false,
		"name": ""+val+" Image",
		"partnerEditable": true,
		"fieldType": "embeddedimage",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4db935efe",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Image Alt Copy",
		"partnerEditable": true,
		"fieldType": "edit",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dbab5eff",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "<h1 style=\"text-align:center;\">Here is a heading<\/h1>\r\n<p style=\"text-align:center;\">This example copy has 160 characters and is an ideal length for this block of copy. Lorem ipsum dolor sit amet, consectet adipiscing elit. Morbi vestibulum eui.<\/p>",
		"supplierPartnerEditable": false,
		"name": ""+val+" Copy",
		"partnerEditable": true,
		"fieldType": "richtext",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dbc05f00",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "Button",
		"supplierPartnerEditable": false,
		"name": ""+val+" CTA Copy",
		"partnerEditable": true,
		"fieldType": "edit",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dbce5f01",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "No",
		"supplierPartnerEditable": false,
		"name": ""+val+" Gate Option",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "Yes,No",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dbd95f02",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "Library Asset",
		"supplierPartnerEditable": false,
		"name": ""+val+" Link Option",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "Library Asset,Print Media,Web Plugin,URL,None",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dbeb5f03",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "File or URL",
		"supplierPartnerEditable": false,
		"name": ""+val+" Link Type",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "File or URL,Video",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983f36ef6ff4b016f0547a1d53bfd",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a9982986f1a9c1c016f240942b22f7b",
		"supplierPartnerEditable": false,
		"name": ""+val+" Library Asset",
		"partnerEditable": false,
		"fieldType": "librarycontent",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "8a9983796f1f36b7016f1ffba83b01c5",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dbf95f04",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a99836d66444ce201665527c1912e63",
		"supplierPartnerEditable": false,
		"name": ""+val+" Print Media",
		"partnerEditable": true,
		"fieldType": "print",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dc0e5f05",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a99827a677710b801677b083bfc1691",
		"supplierPartnerEditable": false,
		"name": ""+val+" Web Plugin",
		"partnerEditable": true,
		"fieldType": "static_panel",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dc1c5f06",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" URL",
		"partnerEditable": false,
		"fieldType": "url",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dc315f07",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Asset Override",
		"partnerEditable": true,
		"fieldType": "url",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": false,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4dc3f5f08",
		"hiddenOption": "",
		"viewableByAgency": false
	}]
}


}
