function ImageRightJSON(key){

var val="Image Right"
if(isNaN(parseInt(key)) ){
	val="Image Right";
}
else {
	val="Image Right "+key;
}
	return {
	"fields": [{
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Header",
		"partnerEditable": true,
		"fieldType": "header",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e41f5f8d",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "#333333",
		"supplierPartnerEditable": false,
		"name": ""+val+" Copy Color",
		"partnerEditable": false,
		"fieldType": "colorpicker",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4445f8f",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Background Image",
		"partnerEditable": false,
		"fieldType": "embeddedimage",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4655f91",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "#ffffff",
		"supplierPartnerEditable": false,
		"name": ""+val+" Background Color",
		"partnerEditable": false,
		"fieldType": "colorpicker",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4585f90",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "http://static.ziftsolutions.com/files/8a9983f36ef6ff4b016f060eb6cf3d95/670x670.png",
		"supplierPartnerEditable": false,
		"name": ""+val+" Image",
		"partnerEditable": true,
		"fieldType": "embeddedimage",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4735f92",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Image Alt Copy",
		"partnerEditable": true,
		"fieldType": "edit",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4825f93",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "<h1>Here is a heading<\/h1>\r\n<p>This example copy has 170 characters and is an ideal length for this block of copy. Lorem ipsum dolor sit amet, consectet adipiscing elit. Morbi vestibulum euismod risus.<\/p>",
		"supplierPartnerEditable": false,
		"name": ""+val+" Copy",
		"partnerEditable": true,
		"fieldType": "richtext",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e48f5f94",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "Button",
		"supplierPartnerEditable": false,
		"name": ""+val+" CTA Copy",
		"partnerEditable": true,
		"fieldType": "edit",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e49c5f95",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "No",
		"supplierPartnerEditable": false,
		"name": ""+val+" Gate Option",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "Yes,No",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4a95f96",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "Library Asset",
		"supplierPartnerEditable": false,
		"name": ""+val+" Link Option",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "Library Asset,Print Media,Web Plugin,URL,None",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4b95f97",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "File or URL",
		"supplierPartnerEditable": false,
		"name": ""+val+" Link Type",
		"partnerEditable": false,
		"fieldType": "radio",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "File or URL,Video",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983f36ef6ff4b016f054e25973c3d",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a9982986f1a9c1c016f240942b22f7b",
		"supplierPartnerEditable": false,
		"name": ""+val+" Library Asset",
		"partnerEditable": false,
		"fieldType": "librarycontent",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "8a9983796f1f36b7016f1ffba83b01c5",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4c75f98",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a99836d66444ce201665527c1912e63",
		"supplierPartnerEditable": false,
		"name": ""+val+" Print Media",
		"partnerEditable": true,
		"fieldType": "print",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4d65f99",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": false,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "8a99827a677710b801677b083bfc1691",
		"supplierPartnerEditable": false,
		"name": ""+val+" Web Plugin",
		"partnerEditable": true,
		"fieldType": "static_panel",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4e55f9a",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": true,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" URL",
		"partnerEditable": false,
		"fieldType": "url",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": true,
		"contextualField": true,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4f25f9b",
		"hiddenOption": "",
		"viewableByAgency": false
	}, {
		"toIgnorePartnerDefaults": true,
		"hiddenOnLead": false,
		"required": false,
		"hiddenOnContacts": false,
		"valuesExtended": "",
		"referenceName": "Ben Test for All Stacker Microsite Fields",
		"dataType": "text",
		"otherDisplayOption": false,
		"defaults": "",
		"supplierPartnerEditable": false,
		"name": ""+val+" Asset Override",
		"partnerEditable": true,
		"fieldType": "url",
		"availableTo123AddContent": false,
		"displayName": "",
		"internalField": false,
		"values": "",
		"referenceType": "Panel",
		"referenceId": "8a9983276cd098de016cd4bee4a52fba",
		"editableByAgency": false,
		"availableToMarcom": false,
		"contextualField": false,
		"uniqueIdentifier": "8a9983166ec980b5016ecdc4e4ff5f9c",
		"hiddenOption": "",
		"viewableByAgency": false
	}]
}


}
